Module1 task3
htmlacademy-nodejs/925901-buy-and-sell-3 pull request #2
Opened 2020-03-27 18:45 UTC by DmytroHV

2020-03-31 21:07 UTC, rmuhamedgaliev requested changes
Ты хорошо постарался! 👍давай обратим внимание на критерии Б5 и Б7. Константы необходимо писать в верхнем регистре, так как так при чтении легче обезопасить себя от переиспользования данной переменной.

2020-03-31 21:07 UTC, rmuhamedgaliev commented on src/service/cli/generate.js
> +};
Нарушен критерий [Б7](https://up.htmlacademy.ru/nodejs/3/criteries#b7). Если мы храним константы в Enum, то переменные внутри должны писаться в верхнем регистре.

2020-03-31 21:07 UTC, rmuhamedgaliev commented on src/service/service.js
> +const {Cli} = require(`./cli`);
Нарушен критерий [Б5](https://up.htmlacademy.ru/nodejs/3/criteries#b5)

2020-04-01 18:58 UTC, dmitriiHV commented
@rmuhamedgaliev да, не обратил внимание на эти критерии, спасибо за замечения. Исправил.

2020-04-01 19:18 UTC, merged